# Auto-generated by setup_urdf.py
# Maps Arduino servo channel → PyBullet revolute joint index
#
# PyBullet revolute joints (document order from rex.urdf):
#   [ 0] motor_front_left_shoulder  (front_left/hip_rotation)
#   [ 1] motor_front_left_leg  (front_left/hip_abduction)
#   [ 2] foot_motor_front_left  (front_left/knee)
#   [ 3] motor_front_right_shoulder  (front_right/hip_rotation)
#   [ 4] motor_front_right_leg  (front_right/hip_abduction)
#   [ 5] foot_motor_front_right  (front_right/knee)
#   [ 6] motor_rear_left_shoulder  (rear_left/hip_rotation)
#   [ 7] motor_rear_left_leg  (rear_left/hip_abduction)
#   [ 8] foot_motor_rear_left  (rear_left/knee)
#   [ 9] motor_rear_right_shoulder  (rear_right/hip_rotation)
#   [10] motor_rear_right_leg  (rear_right/hip_abduction)
#   [11] foot_motor_rear_right  (rear_right/knee)

# servo channel → PyBullet joint index
CHANNEL_TO_JOINT = {
     0:  0,   # front_left / hip_rotation
     1:  1,   # front_left / hip_abduction
     2:  2,   # front_left / knee
     3:  3,   # front_right / hip_rotation
     4:  4,   # front_right / hip_abduction
     5:  5,   # front_right / knee
     6:  6,   # rear_left / hip_rotation
     7:  7,   # rear_left / hip_abduction
     8:  8,   # rear_left / knee
     9:  9,   # rear_right / hip_rotation
    10: 10,   # rear_right / hip_abduction
    11: 11,   # rear_right / knee
}

# Usage in QuadrupedSim._apply_angles():
# for servo_ch, angle in enumerate(angles):
#     pybullet_idx = CHANNEL_TO_JOINT[servo_ch]
#     p.setJointMotorControl2(robot, pybullet_idx, ...)
