#!/usr/bin/env python3
# =============================================================================
# QUADRUPED-K1 // URDF Setup Script
# =============================================================================
# Copies rex.urdf + STL meshes from cloned rex-gym repo into urdf/
# Verifies revolute joint order against your servo channel map
# Runs a PyBullet load test to confirm everything works
#
# Prerequisites:
#   git clone https://github.com/nicrusso7/rex-gym.git deps/rex-gym
#
# Run:
#   python3 setup_urdf.py
# =============================================================================

import re
import sys
import shutil
from pathlib import Path

# ---------------------------------------------------------------------------
# PATHS — confirmed from your ls output
# ---------------------------------------------------------------------------
REX_URDF_SRC = Path("deps/rex-gym/rex_gym/util/pybullet_data/assets/urdf/rex.urdf")
REX_STL_SRC  = Path("deps/rex-gym/rex_gym/util/pybullet_data/assets/urdf/stl")

PROJECT_URDF_DIR = Path("urdf")
PROJECT_STL_DIR  = PROJECT_URDF_DIR / "stl"
URDF_OUT         = PROJECT_URDF_DIR / "rex.urdf"

# ---------------------------------------------------------------------------
# YOUR SERVO CHANNEL MAP
# Order: L1(hip-rot, hip-abd, knee), R1(...), L2(...), R2(...)
# ---------------------------------------------------------------------------
SERVO_MAP = [
    (0,  "front_left",  "hip_rotation"),
    (1,  "front_left",  "hip_abduction"),
    (2,  "front_left",  "knee"),
    (3,  "front_right", "hip_rotation"),
    (4,  "front_right", "hip_abduction"),
    (5,  "front_right", "knee"),
    (6,  "rear_left",   "hip_rotation"),
    (7,  "rear_left",   "hip_abduction"),
    (8,  "rear_left",   "knee"),
    (9,  "rear_right",  "hip_rotation"),
    (10, "rear_right",  "hip_abduction"),
    (11, "rear_right",  "knee"),
]

# Keywords to classify joint names from rex.urdf
LEG_KEYWORDS = {
    "front_left":  ["front_left",  "fl_", "_fl"],
    "front_right": ["front_right", "fr_", "_fr"],
    "rear_left":   ["rear_left",   "rl_", "_rl", "back_left"],
    "rear_right":  ["rear_right",  "rr_", "_rr", "back_right"],
}
JOINT_KEYWORDS = {
    "hip_rotation":  ["shoulder", "abad", "rotation", "hip_x"],
    "hip_abduction": ["hip",      "upper", "thigh",   "hip_y", "_leg"],
    "knee":          ["knee",     "lower", "foot"],
}

# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

def classify_joint(name: str):
    n = name.lower()
    leg = next((k for k, kws in LEG_KEYWORDS.items() if any(kw in n for kw in kws)), None)
    jt  = next((k for k, kws in JOINT_KEYWORDS.items() if any(kw in n for kw in kws)), None)
    return leg, jt


def extract_revolute_joints(urdf_text: str) -> list:
    return re.findall(
        r'<joint\s+name\s*=\s*"([^"]+)"\s+type\s*=\s*"revolute"',
        urdf_text, re.IGNORECASE
    )


def verify_joints(urdf_text: str) -> bool:
    joints = extract_revolute_joints(urdf_text)

    print(f"\n  Revolute joints in URDF ({len(joints)}):")
    for i, j in enumerate(joints):
        leg, jt = classify_joint(j)
        print(f"    [{i:2d}] {j:45s} → {(leg or '?'):12s} / {jt or '?'}")

    print(f"\n  Servo channel map check:")
    mismatches = []
    for ch, exp_leg, exp_type in SERVO_MAP:
        if ch >= len(joints):
            print(f"    CH{ch:02d} [✗] MISSING — URDF only has {len(joints)} revolute joints")
            mismatches.append(ch)
            continue
        jname = joints[ch]
        found_leg, found_type = classify_joint(jname)
        ok = (found_leg == exp_leg) and (found_type == exp_type)
        mark = "✓" if ok else "✗"
        print(f"    CH{ch:02d} [{mark}] {jname:40s}  "
              f"expect={exp_leg}/{exp_type}  got={found_leg}/{found_type}")
        if not ok:
            mismatches.append(ch)

    if mismatches:
        print(f"\n  ⚠  {len(mismatches)} mismatch(es) on channels: {mismatches}")
        print("     Check urdf/joint_map.py — CHANNEL_TO_JOINT will have best-guess fixes")
    else:
        print(f"\n  ✓  All 12 channels match your servo map")

    return len(mismatches) == 0


def write_joint_map(urdf_text: str):
    """Write urdf/joint_map.py with servo channel → PyBullet joint index mapping."""
    joints = extract_revolute_joints(urdf_text)
    out = PROJECT_URDF_DIR / "joint_map.py"

    lines = [
        "# Auto-generated by setup_urdf.py",
        "# Maps Arduino servo channel → PyBullet revolute joint index",
        "#",
        "# PyBullet revolute joints (document order from rex.urdf):",
    ]
    for i, j in enumerate(joints):
        leg, jt = classify_joint(j)
        lines.append(f"#   [{i:2d}] {j}  ({leg}/{jt})")

    lines += ["", "# servo channel → PyBullet joint index", "CHANNEL_TO_JOINT = {"]

    for ch, exp_leg, exp_type in SERVO_MAP:
        # Find best matching joint index
        best = next(
            (i for i, j in enumerate(joints)
             if classify_joint(j) == (exp_leg, exp_type)),
            ch  # fallback: identity mapping
        )
        lines.append(f"    {ch:2d}: {best:2d},   # {exp_leg} / {exp_type}")

    lines += ["}", "",
              "# Usage in QuadrupedSim._apply_angles():",
              "# for servo_ch, angle in enumerate(angles):",
              "#     pybullet_idx = CHANNEL_TO_JOINT[servo_ch]",
              "#     p.setJointMotorControl2(robot, pybullet_idx, ...)",
              ""]

    out.write_text("\n".join(lines))
    print(f"\n  Written → {out}")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    print("=" * 64)
    print("QUADRUPED-K1 // URDF Setup")
    print("=" * 64)

    # ── Check source ──────────────────────────────────────────────
    if not REX_URDF_SRC.exists():
        print(f"\n✗  Not found: {REX_URDF_SRC}")
        print("\n  Run this first:")
        print("    git clone https://github.com/nicrusso7/rex-gym.git deps/rex-gym")
        sys.exit(1)

    if not REX_STL_SRC.exists():
        print(f"\n✗  STL folder not found: {REX_STL_SRC}")
        sys.exit(1)

    # ── Create output dirs ────────────────────────────────────────
    PROJECT_URDF_DIR.mkdir(exist_ok=True)
    PROJECT_STL_DIR.mkdir(exist_ok=True)
    print(f"\n[1/4] Directories ready: {PROJECT_URDF_DIR}/  {PROJECT_STL_DIR}/")

    # ── Copy URDF ─────────────────────────────────────────────────
    shutil.copy2(REX_URDF_SRC, URDF_OUT)
    urdf_text = URDF_OUT.read_text(encoding="utf-8")
    print(f"[2/4] Copied URDF → {URDF_OUT}  ({len(urdf_text):,} chars)")

    # rex.urdf uses relative stl/ paths already — but double-check
    n_pkg = urdf_text.count("package://")
    if n_pkg:
        print(f"      ⚠  {n_pkg} package:// path(s) found — rewriting to stl/filename...")
        urdf_text = re.sub(
            r'filename\s*=\s*"package://[^"]+/([^"/]+\.stl)"',
            lambda m: f'filename="stl/{m.group(1)}"',
            urdf_text, flags=re.IGNORECASE
        )
        URDF_OUT.write_text(urdf_text, encoding="utf-8")
        print(f"      Saved rewritten URDF.")
    else:
        print(f"      ✓  Mesh paths already relative (stl/...) — no changes needed")

    # ── Copy STL meshes ───────────────────────────────────────────
    stl_files = sorted(REX_STL_SRC.glob("*.[sS][tT][lL]"))
    for f in stl_files:
        shutil.copy2(f, PROJECT_STL_DIR / f.name)
    print(f"[3/4] Copied {len(stl_files)} STL files → {PROJECT_STL_DIR}/")
    for f in stl_files:
        print(f"      {f.name}  ({f.stat().st_size/1024:.1f} KB)")

    # ── Verify joint order + write map ───────────────────────────
    print(f"\n[4/4] Joint verification")
    print("-" * 64)
    verify_joints(urdf_text)
    write_joint_map(urdf_text)

    # ── PyBullet load test ────────────────────────────────────────
    print(f"\n{'=' * 64}")
    print("PyBullet load test")
    print("-" * 64)
    try:
        import pybullet as p
        import pybullet_data

        client = p.connect(p.DIRECT)
        p.setGravity(0, 0, -9.81, physicsClientId=client)

        # Load plane using absolute pybullet_data path (avoids search path order issues)
        plane_urdf = str(Path(pybullet_data.getDataPath()) / "plane.urdf")
        p.loadURDF(plane_urdf, physicsClientId=client)

        # Add urdf/ to search path so stl/ meshes resolve correctly, then load robot
        p.setAdditionalSearchPath(str(PROJECT_URDF_DIR.resolve()), physicsClientId=client)
        robot = p.loadURDF(str(URDF_OUT.resolve()), [0, 0, 0.3], physicsClientId=client)

        n_total = p.getNumJoints(robot, physicsClientId=client)
        revolute = []
        print(f"\n  All joints ({n_total} total):")
        for i in range(n_total):
            info  = p.getJointInfo(robot, i, physicsClientId=client)
            jname = info[1].decode()
            jtype = {0: "REVOLUTE", 1: "PRISMATIC", 4: "FIXED"}.get(info[2], f"type={info[2]}")
            print(f"    [{i:2d}] {jname:45s} {jtype}")
            if info[2] == p.JOINT_REVOLUTE:
                revolute.append((i, jname))

        p.disconnect(client)

        print(f"\n  ✓  Loaded successfully")
        print(f"     Total joints    : {n_total}")
        print(f"     Revolute joints : {len(revolute)}")
        if len(revolute) != 12:
            print(f"  ⚠  Expected 12 revolute joints — check URDF for fixed joints")

    except ImportError:
        print("  ℹ  pybullet not installed — skipping load test")
        print("     pip install pybullet")
    except Exception as e:
        print(f"  ✗  Load failed: {e}")

    # ── Final summary ─────────────────────────────────────────────
    print(f"\n{'=' * 64}")
    print("SETUP COMPLETE")
    print("=" * 64)
    print(f"  URDF      : {URDF_OUT}")
    print(f"  Meshes    : {PROJECT_STL_DIR}/ ({len(stl_files)} STL files)")
    print(f"  Joint map : {PROJECT_URDF_DIR}/joint_map.py")
    print()
    print("  Next steps:")
    print("  1. Review urdf/joint_map.py — confirm CHANNEL_TO_JOINT indices")
    print("  2. In quad_env.py set: QuadrupedSim(urdf_path='urdf/rex.urdf')")
    print("  3. Test: python3 quad_env.py sim-gui")


if __name__ == "__main__":
    main()
